---
title: "project"
author: "Rosie Kwon"
date: "2025-10-21"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Load the instacart dataset

```{r}
data("instacart")

dow_labels <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")

instacart = 
  instacart |> 
  mutate(
    order_dow = factor(order_dow, levels = 0:6, labels = dow_labels)
  )
```


1. Barchart : the number of items ordered in each aisle (more than 10000 items ordered)

```{r}
instacart_bar_data =
  instacart |> 
  group_by(aisle) |> 
  summarise(count = n()) |> 
  filter(count > 10000) |> 
  arrange(desc(count))

plot_ly(
  data = instacart_bar_data,
  x = ~count,
  y = ~reorder(aisle, count),
  type = "bar",
  orientation = "h"
) |> 
  layout(
    title = "Number of Items Ordered by Aisle (>10,000)",
    xaxis = list(title = "Number of Items Ordered"),
    yaxis = list(title = "Aisle")
  )
```

2. Box plot : distribution of order time by day of week

```{r}
instacart |> 
  select(order_dow, order_hour_of_day) |> 
  plot_ly(
    x = ~order_dow, y =~order_hour_of_day, color = ~order_dow,
    type = "box", colors = "viridis"
  ) |> 
  layout(
    title = "Distribution of order time by day of week",
    xaxis = list(title = "Day of Week"),
    yaxis = list(title = "Hour of Day (0–23H)")
  )
```


3. Scatter + Line Plot : Orders Started per Hour
```{r}
instacart_line = 
  instacart |>
  filter(add_to_cart_order == 1) |> 
  group_by(order_hour_of_day) |>
  summarise(
    n_orders_started = n(),
    .groups = "drop"
  ) |>
  arrange(order_hour_of_day)

plot_ly(
  data = instacart_line,
  x = ~order_hour_of_day,
  y = ~n_orders_started,
  type = "scatter",
  mode = "markers+lines",
  marker = list(size = 8, opacity = 0.7)
) |>
  layout(
    title = "Orders Started per Hour",
    xaxis = list(title = "Hour of Day (0–23)"),
    yaxis = list(title = "Number of orders")
  )
```

